#!/bin/bash

# Enable the proxy extension in notebook and lab
jupyter serverextension enable --py jupyterlab 

jupyter labextension install jupyterlab_iframe
jupyter labextension install @jupyterlab/server-proxy
jupyter labextension install jupyterlab-dash@0.1.0-alpha.3
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install @bokeh/jupyter_bokeh

jupyter serverextension enable --py jupyterlab_iframe
jupyter serverextension enable --py jupyter_server_proxy
jupyter nbextension enable --py jupyter_bokeh  
jupyter nbextension enable --py jupyterlab-dash@0.1.0-alpha.3

jupyter lab build

code-server --install-extension ms-python.python

# Install the VS code proxy
pip install -e.
